ask/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.conf import settings

from askapp import views

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),

    url('^$', views.main, name='main'),

    url('^users/$', views.users_list, name='users_list'),

    url(r'^questions/$', views.questions_list, name='questions_list'),
    url(r'^questions/add/$', views.add_question, name='add_question'),

    url(r'^user/(?P<user_id>\d+)/$', views.user_page, name='user_page'),
    url(r'^user/(?P<user_id>\d+)/q/$', views.user_question_list, name='user_question_list'),
    url(r'^user/(?P<user_id>\d+)/bm/$', views.user_bookmarks, name='user_bookmarks'),

    url(r'^question/(?P<question_id>\d+)/$', views.question_page, name='question_page',),
    #url(r'^question/(?P<question_id>\d+)/vl/$', views.question_vl, name='question_vl',),
    url(r'^question/(?P<question_id>\d+)/a/$', views.add_answer, name='add_answer',),

    url(r'^question/(?P<question_id>\d+)/bm/$', views.bookmark_question, name='bookmark_question',),
    url(r'^question/(?P<question_id>\d+)/vote/(?P<action>up|down)/$', views.vote_for_question, name='vote_for_question',),

    url(r'^tag/(?P<tag_id>\d+)/$', views.tag_page, name='tag_page'),
    url(r'^tags/$', views.tag_list, name='tag_list'),

    url(r'^account/login/$', login),
    url(r'^account/logout/$', logout,
        {'next_page': '/'}),
    url(r'^account/register/$', views.register, name='register'),

    # static
    (r'^js/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT + '/js'}),

    (r'^css/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT + '/css'}),

    (r'^img/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT + '/img'}),

    (r'^fonts/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT + '/fonts'}),
)

askapp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class Tag(models.Model):
    name = models.CharField(max_length=35)

    def __unicode__(self):
        return '%s' % self.name


class Question(models.Model):
    head = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User)
    date = models.DateTimeField(db_index=True, default=datetime.datetime.now())
    tags = models.ManyToManyField(Tag, related_name='questions', null=True, blank=True)
    up_votes = models.IntegerField(default=0)
    down_votes = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s, Author: %s, Date: %s' % (self.head, self.author, self.date)

    def count_votes(self):
        return self.up_votes - self.down_votes


class Answer(models.Model):
    content = models.TextField()
    question = models.ForeignKey(Question)
    author = models.ForeignKey(User)
    date = models.DateTimeField(db_index=True, default=datetime.datetime.now())
    validity = models.BooleanField(db_index=True, default=False)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s, Author: %s, Date: %s' % (self.content, self.author, self.date)


class QuestionView(models.Model):
    question = models.ForeignKey(Question)
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=40)
    created = models.DateTimeField(default=datetime.datetime.now())

    def __unicode__(self):
        return '%s, %s, %s, %s' % (self.question, self.ip, self.session, self.created)


class Bookmark(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return '%s, %s' % (self.question.head, self.user)


class QVote(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    vote = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s, %s' % (self.question.head, self.user)


class AVote(models.Model):
    answer = models.ForeignKey(Answer)
    user = models.ForeignKey(User)
    vote = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s, %s' % (self.answer, self.user)

askapp/forms.py
# coding=utf-8
from django import forms


def clean_tags(self):
    value = self.cleaned_data['tags']
    if len(value) > 3:
        raise forms.ValidationError("Don't add more than 3 tags.")
    return value


class AddAnswerForm(forms.Form):
    content = forms.CharField(
        widget=forms.Textarea,
        label=''
    )


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=30)
    email = forms.EmailField()
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)


class ValidAnswerForm(forms.Form):
    validity = forms.BooleanField(widget=forms.HiddenInput(), initial=False, required=False)
    a_id = forms.CharField(max_length=100, widget=forms.HiddenInput())

templates/add_question.html
{% extends "base.html" %}

{% block statics %}
    <script type="text/javascript" src="/js/bootstrap-tagsinput.min.js"></script>
    <link href="/css/bootstrap-tagsinput.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
    {% if not user.is_anonymous %}
        <div class="col-sm-10">
            <h2>Add new question:</h2>
            {% if form.subject.errors %}
                <div class="error">
                    <p>Ooops..! Seems that something is wrong! Check your data and submit again, please.</p>
                </div>
            {% endif %}

            <form  method="post" action="/questions/add/" id="question" role="form">
                {% csrf_token %}
                <div class="form-group">
                    <input id="id_head" type="text" name="head" class="form-control" maxlength="50" placeholder="Title" />
                </div>
                <div class="form-group">
                    <textarea id="id_content" rows="10" name="content" cols="40" class="form-control" placeholder="Your question"></textarea>
                </div>
                <p><i>Separate tags with comma</i></p>
                <div class="form-group">
                    <input id="id_tags" class="form-control" data-role="tagsinput" name="tags" type="text" />
                </div>

                <input id="add-question__submit" class="btn btn-primary" type="submit" value="Send" />

                <div id="validity-error" class="validity-error"><i>Make sure you filled all fields.</i></div>
                <div class="clearfix"></div>
            </form>
            <script type="text/javascript" src="/js/add_question.js"></script>
        </div>

    {% else %}
        <div>
            <h2>Sorry</h2>
            <div>
                <p>Anonymous users have no ability to ask questions here.</p>
                <p>You're welcomed to <a href="/account/login/">log in</a> or <a href="/account/register/">register</a>.</p>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/base.html
{% load give_me_users %}
{% load give_me_tags %}

<!DOCTYPE html>
<html lang="ru">

    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>

        <link href="/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="/css/font-awesome.css" rel="stylesheet"/>
        <link href="/css/styles.css" rel="stylesheet"/>
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/settings.js"></script>
        {% block statics %}{% endblock %}
    </head>

    <body>
        <div class="content-container">
            <div class="header">
                <div class="container">
                    <nav class="nav">
                        <a class="nav-item{% if request.path == '/' %} active{% endif %}" href="/">main</a>
                        <a class="nav-item{% if request.path == '/questions/add/' %} active{% endif %}" href="/questions/add/">ask</a>
                        <a class="nav-item{% if request.path == '/questions/' %} active{% endif %}" href="/questions/">answer</a>
                        <a class="nav-item{% if request.path == '/users/' %} active{% endif %}" href="/users/">users</a>
                        <a class="nav-item{% if request.path == '/tags/' %} active{% endif %}" href="/tags/">tags</a>
                        {% include 'includes/login_block.tmpl' %}
                    </nav>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-xs-9">
                        {% block content %}{% endblock %}
                    </div>

                    <div class="col-xs-3 sidebar">
                        <h3>Newcomers</h3>
                        {% show_users %}
                        <h3>Popular tags</h3>
                        {% show_tags %}
                    </div>
                </div>
            </div>
        </div>


        {% comment %}
        <!--DEBUG-->
        <div class="clearfix"></div>
        <pre style="margin-top: 40px;">{% filter force_escape %}{% debug %}{% endfilter %}</pre>
        {% endcomment %}

    </body>

</html>

templates/main.html
{% extends "base.html" %}
{% block title %}Questions and answers{% endblock %}

{% block content %}
        <h2>Hot tags</h2>
        <div class="col-lg-12 col-md-12 tag-list-block">
            {% if tag_list %}
                {% include 'includes/tag_cloud.tmpl' %}
                <div class="clearfix"></div>
                <a href="/tags/" class="see-all">see all</a>
            {% else %}
                <h4>Be first to <a href="/questions/add">ask question</a> and create a tag.</h4>
            {% endif %}
        </div>

        <h2>Know-alls</h2>
        <div class="col-lg-12 col-md-12 user-list-block">
            {% if knowing_users %}
                {% for a_count, q_count, username, first_name, last_name, pk in knowing_users %}
                    {% include 'includes/user_card.tmpl' %}
                {% endfor %}
                <div class="clearfix"></div>
                <p><a href="/users/" class="see-all">see all</a></p>
                <div class="clearfix"></div>
            {% else %}
                <h4>Become first and <a href="/register/">register</a>.</h4>
            {% endif %}
        </div>

        <h2>Most curious</h2>
        <div class="col-lg-12 user-list-block">
            {% if curious_users %}
                {% for q_count, a_count, username, first_name, last_name, pk in curious_users %}
                    {% include 'includes/user_card.tmpl' %}
                {% endfor %}
                <div class="clearfix"></div>
                <p><a href="/users/" class="see-all">see all</a></p>
                <div class="clearfix"></div>
            {% else %}
                <h4>Become first and <a href="/register/">register</a>.</h4>
            {% endif %}
        </div>

{% endblock %}

templates/question.html
{% extends "base.html" %}
{% load paggy %}
{% load substract %}


{% block title %}{{ question.head }}{% endblock %}


{% block content %}

    <script type="text/javascript" src="/js/question.js"></script>


    <div class="question-post">
        <h2>{{ question.head }}</h2>

        {% include 'includes/entry_card.tmpl' with type="question" %}

        <div>{{ question.content }}</div>
        {%for tag in question.tags.all %}
            <a href="/tag/{{ tag.pk }}/"><span class="badge badge-inverse">{{ tag }}</span></a>
        {% endfor %}
        <div class="clearfix"></div>
    </div>

    <div id="answer-list">
        <h3><span id="ans_num">{{ ans_num }}</span> answers</h3>
        {% if ans_num == 0 %}
            <p id="noanswer">No one replied yet. Be first!</p>
        {% else %}
            {% for answer in answers %}
                <div class="answer-list__item">
                    {% include 'includes/entry_card.tmpl' with type="answer" %}
                    <p>{{ answer.content }}</p>
                    <div class="clearfix"></div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% include 'includes/pagination.tmpl' with objectName="answers" %}

    {% if not user.is_anonymous %}
        <h4>Suggest your answer</h4>
        <form class="add-answer" method="post">
            {% csrf_token %}
            {{ form_add.as_p }}
            <input class="author" type="hidden" name="username" value="{{ user.pk }}" />
            <input class="q-id" type="hidden" name="q_id" value="{{ question.pk }}" />
            <input id="sendAnswer" class="btn btn-primary" type="submit" value="Send" />
        </form>
    {% else %}
        <h4><a href="/account/login/">Log in</a> and add your answer.</h4>
    {% endif %}

{% endblock %}

templates/question_list.html
{% extends "base.html" %}

{% load paggy %}
{% load substract %}

{% block title %}Latest questions{% endblock %}

{% block content %}
    <h2>Latest questions</h2>
    {% if questions %}
        {% for question in questions %}
            {% include 'includes/question_list_item.tmpl' %}
        {% endfor %}
    {% else %}
        <p>No questions yet</p>
    {% endif %}

    {% include 'includes/pagination.tmpl' with objectName="questions" %}
{% endblock %}

templates/register.html
{% extends "base.html" %}


{% block content %}
    <div class="form">
        <h2>Sign up</h2>

        {% if error %}
            <ul class="errorlist">
                <li>{{ error }}</li>
            </ul>
        {% endif %}

        <form id="registerForm" method="post" action="/account/register/" role="form">
            {% csrf_token %}

            <div class="form-group">
                <div>Username</div>
                <input type="text" id="username" class="formInputText form-control" name="username" maxlength="30">
            </div>
            <div class="form-group">
                <div>First name</div>
                <input type="text" id="first_name" class="formInputText form-control" name="first_name" maxlength="30">
            </div>
            <div class="form-group">
                <div>Last name</div>
                <input type="text" id="last_name" class="formInputText form-control" name="last_name" maxlength="30">
            </div>
            <div class="form-group">
                <div>Password</div>
                <input type="password" id="password" class="formInputText form-control" name="password" maxlength="30">
            </div>
            <div class="form-group">
                <div>E-mail</div>
                <input type="email" id="email" class="formInputText form-control" name="email" maxlength="30">
            </div>

            <input class="btn btn-primary btn-login" value="Register" type="submit">
        </form>
        <a href="/account/login/" class="btn btn-primary btn-login">Log in</a>
        <div class="clearfix"></div>
    </div>
{% endblock %}

templates/show_tags.html
{% if tags %}
    {% for tag in tags %}
        <div>
            <a href="/tag/{{tag.pk}}"><span class="badge badge-inverse">{{tag}}</span></a>
            <p class="show-tags__count">x {{tag.count}}</p>
        </div>
    {% endfor %}
{% else %}
    No tags yet
{% endif %}

templates/show_users.html
{% if users %}
    {% for user in users %}
        <div>
            {% if  user.first_name and user.last_name %}
                <a href="/user/{{user.pk}}/">{{ user.first_name }} {{user.last_name}}</a>
            {% else %}
                <a href="/user/{{user.pk}}/">{{ user.username}}</a>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    No users
{% endif %}

templates/tag.html
{% extends "base.html" %}
{% load substract %}

{% block title %}{{ tag }}{% endblock %}

{% block content %}
    <div class="col-sm-12">
        <h2>{{ tag.name|upper }}</h2>

        <h3>Tagged questions ({{ size }} in total)</h3>
        <div class="tag-question-list">
            {% for question in question_list %}
                {% include 'includes/question_list_item.tmpl' %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/tag_list.html
{% extends "base.html" %}
{% block title %}Tags{% endblock %}

{% block content %}
    <h2>All tags</h2>
    {% if tag_list %}
        <div class="col-sm-12" class="tag-list">
            {% if tag_list %}{% include 'includes/tag_cloud.tmpl' %}{% endif %}
        </div>
    {% else %}
        <h4>Be first to <a href="/questions/add">ask question</a> and create a tag.</h4>
    {% endif %}
{% endblock %}

templates/user.html
{% extends "base.html" %}
{% load give_me_tags %}

{% block title %}{{ page_user.username }} profile{% endblock %}

{% block content %}
    <div class="col-md-12">
        <div class="user-activity__info">
            <h2>
                <a href="/user/{{ page_user.pk }}">
                    {% if page_user.first_name or page_user.last_name %}
                        {{ page_user.first_name }}&nbsp;{{ page_user.last_name }}
                    {% else %}
                        {{ page_user.username }}
                    {% endif %}
                </a>
            </h2>
            <table>
                {% if page_user.email %}
                    <tr>
                        <td><b>e-mail</b></td><td>{{ page_user.email }}</td>
                    </tr>
                {% endif %}
                {% if page_user.last_login %}
                    <tr>
                        <td><b>last seen</b></td><td>{{ page_user.last_login }}</td>
                    </tr>
                {% endif %}
            </table>
        </div>

        {% if tag_list %}
            <div class="user-activity__tags">
                {% for tag in tag_list %}
                    <a href="/tag/{{ tag.pk }}"><span class="badge badge-info">{{ tag.name }}</span></a>
                {% endfor %}
            </div>

        {% endif %}

        <div class="clearfix"></div>

        {% block userdata  %}
            <div class="user-activity">
                <h3>Latest activity</h3>
                <div class="col-sm-6">
                    {% if asked_num > 0 %}
                        <h4>Questions ({{ asked_num }} in total)</h4>
                        {% for question in questions %}
                            <li>
                                <a href="/question/{{ question.pk }}">{{ question.head }}</a>
                            </li>
                        {% endfor %}
                        <a class="see-all" href="/user/{{ page_user.pk }}/q/">see all</a>
                    {% else %}
                        <h4>Questions</h4>
                        <p>User added no questions yet</p>
                    {% endif %}
                </div>
                <div class="col-sm-6">
                    {% if bm_num != 0 %}
                        <h4>Bookmarks ({{ bm_num }} in total)</h4>
                        {% for bookmark in bookmarks %}
                            <li>
                                <a href="/question/{{ bookmark.question.pk }}/">{{ bookmark.question.head }}</a>
                            </li>
                        {% endfor %}
                        <a class="see-all" href="/user/{{ page_user.pk }}/bm/">see all</a>
                    {% else %}
                        <h4>Bookmarks</h4>
                        <p>User has no bookmarks yet</p>
                    {% endif %}
                </div>
            </div>
        {% endblock %}
    </div>

{% endblock %}

templates/user_bm.html
{% extends "user.html" %}
{% load paggy %}
{% load substract %}

{% block title %}{{ user.username }} bookmarks{% endblock %}

{% block userdata %}
    <h2>{{ page_user.username }}'s bookmarks</h2>
    {% if bookmark_list %}
        {% for bookmark in bookmark_list %}
            {% include 'includes/question_list_item.tmpl' with object='bm' %}
        {% endfor %}
    {% else %}
        <p>User has no bookmarks yet.</p>
    {% endif %}
{% endblock %}

templates/user_list.html
{% extends "base.html" %}

{% load filter %}
{% load staticfiles %}

{% block title %}Users{% endblock %}

{%block content%}
    <h2>Last joined users</h2>

    <div class="user-list">
        {% if users %}
            {% for a_count, q_count, username, first_name, last_name, pk in users %}
                {% include 'includes/user_card.tmpl' %}
            {% endfor %}
        {% else %}
            <p>No users yet</p>
        {% endif %}
    </div>

    {% include 'includes/pagination.tmpl' with objectName="users" %}
{%endblock%}

templates/user_q.html
{% extends "user.html" %}
{% load paggy %}
{% load substract %}

{% block title %}{{ pageUser.username }} questions{% endblock %}


{% block userdata %}
    <h2>Questions by {{ page_user.username }}</h2>
    {% if questions %}
        {% for question in questions %}
            {% include 'includes/question_list_item.tmpl' %}
        {% endfor %}
    {% else %}
        <p>User asked no questions yet.</p>
    {% endif %}
{% endblock %}